# DQN Algorithm Hyperparameters
algorithm:
  learning_rate: 0.001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  buffer_size: 10000
  batch_size: 64
  target_update: 100
  hidden_size: 128 